title: Star Citizen Handbook
description: A bilingual guide for Star Citizen players
baseurl: ""
url: "https://ongxeno.github.io/star-citizen-handbook"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:path/

# Multilingual settings
languages: ["th", "en"]
default_lang: "th"
exclude_from_localization: ["assets", "js", "images", "css"]
parallel_localization: true

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
      game_version: "Alpha 3.23.1"
