# hugo.toml
baseURL = 'https://ongxeno.github.io/star-citizen-handbook/'
theme = "docsy"
title = "Star Citizen Handbook"

# Enable features
enableGitInfo = true
enableRobotsTXT = true

# Language and content organization
contentDir = "content"
defaultContentLanguageInSubdir = true

# Main language configuration
defaultContentLanguage = "th"

[languages]
  [languages.th]
    title = "คู่มือ Star Citizen"
    languageName = "ภาษาไทย"
    contentDir = "content/th"
    weight = 1
  [languages.en]
    title = "Star Citizen Handbook"
    languageName = "English"
    contentDir = "content/en"
    weight = 2

# Docsy theme specific settings (can be customized later)
[params]
  github_repo = "https://github.com/ongxeno/star-citizen-handbook"
  version_menu = "Game Version"

# Hugo Modules for theme
[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false
  [[module.imports.mounts]]
    source = "assets"
    target = "assets"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports.mounts]]
    source = "static"
    target = "static"
  [[module.imports.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/scss"
    target = "assets/vendor/Font-Awesome/scss"
  [[module.imports.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"
